# Outputting
permalink: /:categories/:year/:month/:day/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Sébastien Pujadas  # Site title
name:             Sébastien Pujadas              # Your name
avatar:           /theme/img/spujadas.jpg   # Path to an avatar image

# The theme uses the baseurl throughout, which is useful for running the entire
# site under a subdir, like for this GitHub Pages deployment as a project site.
baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_pages"]

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
